# Generated by Django 5.2.8 on 2025-11-30 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0002_initial'),
        ('tutors', '0002_tutoravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advising_sessions', to='tutoring_sessions.session')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.tutor')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
