# Generated by Django 5.2.8 on 2025-11-27 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session_request', 'Session Request'), ('session_confirmed', 'Session Confirmed'), ('session_cancelled', 'Session Cancelled'), ('session_completed', 'Session Completed'), ('announcement', 'Announcement'), ('feedback_received', 'Feedback Received'), ('technical_report', 'Technical Report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('session_id', models.IntegerField(blank=True, help_text='Related session ID', null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_broadcast', models.BooleanField(default=False, help_text='Broadcast to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, help_text='Specific user (null = broadcast to all)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_1c662a_idx'), models.Index(fields=['is_broadcast', '-created_at'], name='notificatio_is_broa_c11338_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('session_id', models.IntegerField(blank=True, help_text='Subscribe to specific session', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Observer',
                'verbose_name_plural': 'Notification Observers',
                'unique_together': {('user', 'event_type', 'session_id')},
            },
        ),
    ]
