# Generated by Django 5.2.8 on 2025-11-27 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('students', '0001_initial'),
        ('tutoring_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutoring_sessions.enrollment'),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to='students.student'),
        ),
        migrations.AddField(
            model_name='technicalreport',
            name='user',
            field=models.ForeignKey(help_text='User who reported the issue', on_delete=django.db.models.deletion.CASCADE, related_name='technical_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='technicalreport',
            index=models.Index(fields=['-created_at'], name='feedback_te_created_7b5801_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalreport',
            index=models.Index(fields=['status'], name='feedback_te_status_a35e67_idx'),
        ),
    ]
