# Generated by Django 5.2.8 on 2025-11-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
        ('students', '0001_initial'),
        ('tutoring_sessions', '0002_initial'),
        ('tutors', '0002_tutoravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(default=0)),
                ('topics_covered', models.IntegerField(default=0)),
                ('comprehension_level', models.IntegerField(default=0)),
                ('goals_achieved', models.IntegerField(default=0)),
                ('area_for_improvement', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='tutoring_sessions.enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_sessions.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.tutor')),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
    ]
